## Section A : Data Structures and Control Structures

In [1]:
list=[5,7,8,9,12]
list

[5, 7, 8, 9, 12]

In [19]:
list.append(20) #append an element in last
list

[5, 7, 8, 9, 12, 20]

In [20]:
list.extend([22,24]) #insert multiple elements at a time
list

[5, 7, 8, 9, 12, 20, 22, 24]

In [21]:
list.insert(4,10) #insert an element at specific position
list

[5, 7, 8, 9, 10, 12, 20, 22, 24]

In [22]:
list.remove(20) #removes the element from the list,removes the first occurance of an elemnt
list

[5, 7, 8, 9, 10, 12, 22, 24]

In [23]:
list.pop() #deletes the value by an index,by default the last value

24

In [24]:
list

[5, 7, 8, 9, 10, 12, 22]

In [25]:
list.pop(3) #the value of index 3 will be deleted

9

In [26]:
list

[5, 7, 8, 10, 12, 22]

In [28]:
list.clear() #empties the list by clearing all the elements
list

[]

In [30]:
list1=[10,20,30,40,50]
list1

[10, 20, 30, 40, 50]

In [31]:
list1.index(30) #finds the position of the value
list1

[10, 20, 30, 40, 50]

In [32]:
list1.count(20) #counts how many times an value is present in the list

1

In [33]:
list2=[4,2,9,1,6]
list2

[4, 2, 9, 1, 6]

In [35]:
list2.sort() #sort the vlaues in an ascending values
list2

[1, 2, 4, 6, 9]

In [36]:
list2.reverse() #reverse the values of the list
list2

[9, 6, 4, 2, 1]

In [37]:
tuple=('deepika','shwetha','shruthi')
tuple

('deepika', 'shwetha', 'shruthi')

In [38]:
tuple[1]='divya' #we can not change the value present in the tuple

TypeError: 'tuple' object does not support item assignment

In [39]:
set={1,2,2,3,4,5,6,5,7,8,7,8,9,10}
set

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [41]:
dict1={'Name':['Adithya','Nikhil','Abhi','Ajay'],
      'Age':[24,32,25,28],
      'City':['Chennai','Bangalore','Bangalore','pune']}
dict1

{'Name': ['Adithya', 'Nikhil', 'Abhi', 'Ajay'],
 'Age': [24, 32, 25, 28],
 'City': ['Chennai', 'Bangalore', 'Bangalore', 'pune']}

In [42]:
dict2={'Age':[25,26,27,28]}
dict2

{'Age': [25, 26, 27, 28]}

In [43]:
dict1.update(dict2) #update the dict1 from dict2.It will replace the all values of the dict1 by dict2

In [44]:
dict1

{'Name': ['Adithya', 'Nikhil', 'Abhi', 'Ajay'],
 'Age': [25, 26, 27, 28],
 'City': ['Chennai', 'Bangalore', 'Bangalore', 'pune']}

In [47]:
dict1.setdefault('Email',['adithya@gmail.com','nikhil@gmail.com','abhi@gmail.com','ajay@gmail.com'])
dict1

{'Name': ['Adithya', 'Nikhil', 'Abhi', 'Ajay'],
 'Age': [25, 26, 27, 28],
 'City': ['Chennai', 'Bangalore', 'Bangalore', 'pune'],
 'Email': ['adithya@gmail.com',
  'nikhil@gmail.com',
  'abhi@gmail.com',
  'ajay@gmail.com']}

In [48]:
dict1 #updated version of dict1

{'Name': ['Adithya', 'Nikhil', 'Abhi', 'Ajay'],
 'Age': [25, 26, 27, 28],
 'City': ['Chennai', 'Bangalore', 'Bangalore', 'pune'],
 'Email': ['adithya@gmail.com',
  'nikhil@gmail.com',
  'abhi@gmail.com',
  'ajay@gmail.com']}

In [50]:
age = 20

if age < 18: #checking the age of a person is less than 18 or not
    print("The person is not eligible to vote")
else:
    print("The person is eligible to vote")

The person is eligible to vote


In [66]:
marks=86

if marks >= 90:
    print("The garde is A")
elif marks >= 75 and marks <= 89:
    print("The grade is B")
elif marks >= 50 and marks <= 74:
    print("The grade is C")
elif marks < 50:
    print("Fail")
else:
    print("Invalid")

The grade is B


In [76]:
num = int(input("Enter the number"))

if num > 0:
    if num%2 == 0:
        print("The number is positive and is even")
    else:
        print("The number is positive and is odd")
elif num < 0:
    print("The number is nagative")
else:
    print("The number is zero")

Enter the number -9


The number is nagative


## Section-B Numpy

In [79]:
import numpy as np
scalar=np.array(5)
scalar

array(5)

In [80]:
one_dim=np.array([1,2,3,4,5]) #craetion of one dimensional array
one_dim

array([1, 2, 3, 4, 5])

In [92]:
twod_array=np.arange(10,61,10) #arranging the value from 10 to 60 step by 10
twod_array

array([10, 20, 30, 40, 50, 60])

In [94]:
two_dim=twod_array.reshape(2,3) #reshaping the 2d array 
two_dim

array([[10, 20, 30],
       [40, 50, 60]])

In [98]:
two_arr=np.random.randint(1,100,16) #generating the random numbers using np.random.randint()
two_arr

array([65, 85,  2, 51, 77, 73, 46, 42, 44, 35, 53, 43, 13, 13, 18, 37])

In [99]:
two_arr.reshape(4,4)

array([[65, 85,  2, 51],
       [77, 73, 46, 42],
       [44, 35, 53, 43],
       [13, 13, 18, 37]])

In [103]:
import pandas as pd
array_2d=np.array([[2,3,5],[4,5,6],[5,6,7]])
array_2d

array([[2, 3, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [106]:
df = pd.DataFrame(array_2d,columns=['A','B','C'])
df

,A,B,C
0,2,3,5
1,4,5,6
2,5,6,7


## Section C: Exploring Pandas

In [150]:
data = {'Name':['Shilpa','Mythri','Shwetha','Shruthi','Divya','Uday','Akshay','Vinay','Chinamay','Divya'],
    'Age':[23,21,33,31,32,33,34,35,25,32],
    'City':['Bangalore','Pune','Kodagu','Kashmir','Bangalore','Bangalore','Chennai','Vaynad','Hyderabad','Bangalore'],
    'Salary':[50000,35000,42000,60000,45000,35000,None,40000,None,45000,]
}

In [151]:
df3 = pd.DataFrame(data) 
df3

,Name,Age,City,Salary
0,Shilpa,23,Bangalore,50000.0
1,Mythri,21,Pune,35000.0
2,Shwetha,33,Kodagu,42000.0
3,Shruthi,31,Kashmir,60000.0
4,Divya,32,Bangalore,45000.0
5,Uday,33,Bangalore,35000.0
6,Akshay,34,Chennai,NaN
7,Vinay,35,Vaynad,40000.0
8,Chinamay,25,Hyderabad,NaN
9,Divya,32,Bangalore,45000.0


In [152]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [153]:
df3.describe()

,Age,Salary
count,10.000000,8.000000
mean,29.900000,44000.000000
std,4.976612,8246.211251
min,21.000000,35000.000000
25%,26.500000,38750.000000
50%,32.000000,43500.000000
75%,33.000000,46250.000000
max,35.000000,60000.000000


In [154]:
print(df3[['Name','City']]) #selecting only the name and city column

       Name       City
0    Shilpa  Bangalore
1    Mythri       Pune
2   Shwetha     Kodagu
3   Shruthi    Kashmir
4     Divya  Bangalore
5      Uday  Bangalore
6    Akshay    Chennai
7     Vinay     Vaynad
8  Chinamay  Hyderabad
9     Divya  Bangalore


In [155]:
df3.drop('City',axis=1,inplace=True) #here axis=1 means the column and inplace=True is we deleted the city column permenantly in df3.
                                     #df3 itself is changed permenantly
df3

,Name,Age,Salary
0,Shilpa,23,50000.0
1,Mythri,21,35000.0
2,Shwetha,33,42000.0
3,Shruthi,31,60000.0
4,Divya,32,45000.0
5,Uday,33,35000.0
6,Akshay,34,NaN
7,Vinay,35,40000.0
8,Chinamay,25,NaN
9,Divya,32,45000.0


In [157]:
df3['Salary'].fillna(df3['Salary'].mean()) #taking the salary columns and filling the Nan value that is missing values with the mean value.

0    50000.0
1    35000.0
2    42000.0
3    60000.0
4    45000.0
5    35000.0
6    44000.0
7    40000.0
8    44000.0
9    45000.0
Name: Salary, dtype: float64

In [159]:
df3.drop_duplicates(inplace=True)  #dropping the duplicate value in df3 permenantly
df3

,Name,Age,Salary
0,Shilpa,23,50000.0
1,Mythri,21,35000.0
2,Shwetha,33,42000.0
3,Shruthi,31,60000.0
4,Divya,32,45000.0
5,Uday,33,35000.0
6,Akshay,34,NaN
7,Vinay,35,40000.0
8,Chinamay,25,NaN
